name: Deploy

on:
  push:
    branches:
      - master

env:
  DEVMAJ: devmaj
  RELCERT: relcert
  MAJSTG: majstg
  PRD: prd
  AWS_REGION: us-west-2

jobs:
  tag-release:
    name: 'Tag release?'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v2

      - name: Configure prd AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PRD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PRD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Store lambda version
        id: store_lambda_version
        run: |
          version=$(./manageAWS.sh get_latest_version)
          echo $version
          echo "::set-output name=lambda-version::${version}"
        shell: bash
        env:
          ENV_NAME: ${{ env.PRD }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.store_lambda_version.outputs.lambda-version }}

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
