name: Destroy ephemeral stack when PR closes

on:
  pull_request:
    types:
      - closed

env:
  EPHEMERAL: pr-${{ github.event.pull_request.number }}
  AWS_REGION: us-west-2

jobs:
  destroy-ephemeral-stack:
    name: 'Destroy ephemeral stack when PR closes.'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Destroy ephemeral
        run: make destroy
        env:
          ENV_NAME: ${{ env.EPHEMERAL }}