name: Remove labels

on:
  pull_request

jobs:
  remove_label:
    runs-on: ubuntu-latest
    name: remove label
    steps:
      - name: remove label
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: deploy pre-prod
          type: remove

      - name: remove label
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: ship to prod
          type: remove